# docker-compose.yml
# 開発環境用のdocker-compose
version: '3'
services:
 database:
   image: mysql:5.7
   ports:
     - 3306:3306
   volumes:
     - mysql-datavolume:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: root
 app:
   build:
     context: .
     dockerfile: ./docker/rails/Dockerfile
   command: bundle exec rails s -p 3000 -b '0.0.0.0'
   ports:
     - "3000:3000"
   volumes:
     - .:/sokuwork
     - bundle:/usr/local/bundle
   tty: true
   environment:
     EDITOR: vim
     RAILS_MAX_THREADS: 5
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
     MYSQL_HOST: database
     RAILS_MASTER_KEY: 9fef6c1b0c2c49b395d955c6dbdcea72
   links:
     - database
 server:
   build:
     context: docker/nginx
   volumes:
     - ./nginx/log:/var/log/nginx
     - "bundle:/usr/local/bundle"
   depends_on:
     - app
   ports:
     - 80:80
volumes:
 bundle:
   driver: local
 mysql-datavolume:
   driver: local
