version: 2.1
jobs:
 build:
   docker:
     - image: circleci/ruby:2.6.1-node
       environment:
         RAILS_ENV: test
     - image: circleci/mysql:5.7-ram
       environment:
         MYSQL_ALLOW_EMPTY_PASSWORD: true
