Category.find_or_create_by(name:"飲食・フード")
Category.find_or_create_by(name:"接客・サービス")
Category.find_or_create_by(name:"販売")
Category.find_or_create_by(name:"オフィスワーク")
Category.find_or_create_by(name:"軽作業・配送")
Category.find_or_create_by(name:"イベント・キャンペーン")
